version: '2'
services:
    node:
        build: .
        container_name: krikey
        ports:
            - '5000:5000'
        environment:
            PORT: 5000
        volumes:
            - .:/usr/src/app
        restart: always
volumes:
    data: {}